steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'functions', 'deploy', 'paellers', '--source', 'paellers', '--trigger-http', '--runtime', 'nodejs14', '--allow-unauthenticated', '--region', 'us-cental1']
timeout: '1200s'
